/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ComoUsarRouteImport } from './routes/como-usar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ObrasIndexRouteImport } from './routes/obras.index'
import { Route as ObrasNumRouteImport } from './routes/obras.$num'

const ComoUsarRoute = ComoUsarRouteImport.update({
  id: '/como-usar',
  path: '/como-usar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrasIndexRoute = ObrasIndexRouteImport.update({
  id: '/obras/',
  path: '/obras/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrasNumRoute = ObrasNumRouteImport.update({
  id: '/obras/$num',
  path: '/obras/$num',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/como-usar': typeof ComoUsarRoute
  '/obras/$num': typeof ObrasNumRoute
  '/obras/': typeof ObrasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/como-usar': typeof ComoUsarRoute
  '/obras/$num': typeof ObrasNumRoute
  '/obras': typeof ObrasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/como-usar': typeof ComoUsarRoute
  '/obras/$num': typeof ObrasNumRoute
  '/obras/': typeof ObrasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/como-usar' | '/obras/$num' | '/obras/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/como-usar' | '/obras/$num' | '/obras'
  id: '__root__' | '/' | '/como-usar' | '/obras/$num' | '/obras/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComoUsarRoute: typeof ComoUsarRoute
  ObrasNumRoute: typeof ObrasNumRoute
  ObrasIndexRoute: typeof ObrasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/como-usar': {
      id: '/como-usar'
      path: '/como-usar'
      fullPath: '/como-usar'
      preLoaderRoute: typeof ComoUsarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obras/': {
      id: '/obras/'
      path: '/obras'
      fullPath: '/obras/'
      preLoaderRoute: typeof ObrasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obras/$num': {
      id: '/obras/$num'
      path: '/obras/$num'
      fullPath: '/obras/$num'
      preLoaderRoute: typeof ObrasNumRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComoUsarRoute: ComoUsarRoute,
  ObrasNumRoute: ObrasNumRoute,
  ObrasIndexRoute: ObrasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
