/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as QrcodesRouteImport } from './routes/qrcodes'
import { Route as ParticipeRouteImport } from './routes/participe'
import { Route as LinhasDaVidaRouteImport } from './routes/linhas-da-vida'
import { Route as InstitutoRouteImport } from './routes/instituto'
import { Route as EspacosDeMemoriaRouteImport } from './routes/espacos-de-memoria'
import { Route as ElifasAndreatoRouteImport } from './routes/elifas-andreato'
import { Route as EditarRouteImport } from './routes/editar'
import { Route as ComoUsarRouteImport } from './routes/como-usar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AcervoRouteImport } from './routes/acervo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QrcodesIndexRouteImport } from './routes/qrcodes.index'
import { Route as ParticipeIndexRouteImport } from './routes/participe.index'
import { Route as ObrasIndexRouteImport } from './routes/obras.index'
import { Route as InstitutoIndexRouteImport } from './routes/instituto.index'
import { Route as EspacosDeMemoriaIndexRouteImport } from './routes/espacos-de-memoria.index'
import { Route as ElifasAndreatoIndexRouteImport } from './routes/elifas-andreato.index'
import { Route as AcervoIndexRouteImport } from './routes/acervo.index'
import { Route as QrcodesImprimirRouteImport } from './routes/qrcodes.imprimir'
import { Route as ObrasNumRouteImport } from './routes/obras.$num'
import { Route as ApiPublicObraImagemNumRouteImport } from './routes/api/public/obra-imagem.$num'
import { Route as ApiPublicObraAudioNumRouteImport } from './routes/api/public/obra-audio.$num'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const QrcodesRoute = QrcodesRouteImport.update({
  id: '/qrcodes',
  path: '/qrcodes',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipeRoute = ParticipeRouteImport.update({
  id: '/participe',
  path: '/participe',
  getParentRoute: () => rootRouteImport,
} as any)
const LinhasDaVidaRoute = LinhasDaVidaRouteImport.update({
  id: '/linhas-da-vida',
  path: '/linhas-da-vida',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutoRoute = InstitutoRouteImport.update({
  id: '/instituto',
  path: '/instituto',
  getParentRoute: () => rootRouteImport,
} as any)
const EspacosDeMemoriaRoute = EspacosDeMemoriaRouteImport.update({
  id: '/espacos-de-memoria',
  path: '/espacos-de-memoria',
  getParentRoute: () => rootRouteImport,
} as any)
const ElifasAndreatoRoute = ElifasAndreatoRouteImport.update({
  id: '/elifas-andreato',
  path: '/elifas-andreato',
  getParentRoute: () => rootRouteImport,
} as any)
const EditarRoute = EditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoUsarRoute = ComoUsarRouteImport.update({
  id: '/como-usar',
  path: '/como-usar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcervoRoute = AcervoRouteImport.update({
  id: '/acervo',
  path: '/acervo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QrcodesIndexRoute = QrcodesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QrcodesRoute,
} as any)
const ParticipeIndexRoute = ParticipeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ParticipeRoute,
} as any)
const ObrasIndexRoute = ObrasIndexRouteImport.update({
  id: '/obras/',
  path: '/obras/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutoIndexRoute = InstitutoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InstitutoRoute,
} as any)
const EspacosDeMemoriaIndexRoute = EspacosDeMemoriaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EspacosDeMemoriaRoute,
} as any)
const ElifasAndreatoIndexRoute = ElifasAndreatoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ElifasAndreatoRoute,
} as any)
const AcervoIndexRoute = AcervoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AcervoRoute,
} as any)
const QrcodesImprimirRoute = QrcodesImprimirRouteImport.update({
  id: '/imprimir',
  path: '/imprimir',
  getParentRoute: () => QrcodesRoute,
} as any)
const ObrasNumRoute = ObrasNumRouteImport.update({
  id: '/obras/$num',
  path: '/obras/$num',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicObraImagemNumRoute = ApiPublicObraImagemNumRouteImport.update({
  id: '/api/public/obra-imagem/$num',
  path: '/api/public/obra-imagem/$num',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicObraAudioNumRoute = ApiPublicObraAudioNumRouteImport.update({
  id: '/api/public/obra-audio/$num',
  path: '/api/public/obra-audio/$num',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acervo': typeof AcervoRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/como-usar': typeof ComoUsarRoute
  '/editar': typeof EditarRoute
  '/elifas-andreato': typeof ElifasAndreatoRouteWithChildren
  '/espacos-de-memoria': typeof EspacosDeMemoriaRouteWithChildren
  '/instituto': typeof InstitutoRouteWithChildren
  '/linhas-da-vida': typeof LinhasDaVidaRoute
  '/participe': typeof ParticipeRouteWithChildren
  '/qrcodes': typeof QrcodesRouteWithChildren
  '/sobre': typeof SobreRoute
  '/obras/$num': typeof ObrasNumRoute
  '/qrcodes/imprimir': typeof QrcodesImprimirRoute
  '/acervo/': typeof AcervoIndexRoute
  '/elifas-andreato/': typeof ElifasAndreatoIndexRoute
  '/espacos-de-memoria/': typeof EspacosDeMemoriaIndexRoute
  '/instituto/': typeof InstitutoIndexRoute
  '/obras/': typeof ObrasIndexRoute
  '/participe/': typeof ParticipeIndexRoute
  '/qrcodes/': typeof QrcodesIndexRoute
  '/api/public/obra-audio/$num': typeof ApiPublicObraAudioNumRoute
  '/api/public/obra-imagem/$num': typeof ApiPublicObraImagemNumRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/como-usar': typeof ComoUsarRoute
  '/editar': typeof EditarRoute
  '/linhas-da-vida': typeof LinhasDaVidaRoute
  '/sobre': typeof SobreRoute
  '/obras/$num': typeof ObrasNumRoute
  '/qrcodes/imprimir': typeof QrcodesImprimirRoute
  '/acervo': typeof AcervoIndexRoute
  '/elifas-andreato': typeof ElifasAndreatoIndexRoute
  '/espacos-de-memoria': typeof EspacosDeMemoriaIndexRoute
  '/instituto': typeof InstitutoIndexRoute
  '/obras': typeof ObrasIndexRoute
  '/participe': typeof ParticipeIndexRoute
  '/qrcodes': typeof QrcodesIndexRoute
  '/api/public/obra-audio/$num': typeof ApiPublicObraAudioNumRoute
  '/api/public/obra-imagem/$num': typeof ApiPublicObraImagemNumRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acervo': typeof AcervoRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/como-usar': typeof ComoUsarRoute
  '/editar': typeof EditarRoute
  '/elifas-andreato': typeof ElifasAndreatoRouteWithChildren
  '/espacos-de-memoria': typeof EspacosDeMemoriaRouteWithChildren
  '/instituto': typeof InstitutoRouteWithChildren
  '/linhas-da-vida': typeof LinhasDaVidaRoute
  '/participe': typeof ParticipeRouteWithChildren
  '/qrcodes': typeof QrcodesRouteWithChildren
  '/sobre': typeof SobreRoute
  '/obras/$num': typeof ObrasNumRoute
  '/qrcodes/imprimir': typeof QrcodesImprimirRoute
  '/acervo/': typeof AcervoIndexRoute
  '/elifas-andreato/': typeof ElifasAndreatoIndexRoute
  '/espacos-de-memoria/': typeof EspacosDeMemoriaIndexRoute
  '/instituto/': typeof InstitutoIndexRoute
  '/obras/': typeof ObrasIndexRoute
  '/participe/': typeof ParticipeIndexRoute
  '/qrcodes/': typeof QrcodesIndexRoute
  '/api/public/obra-audio/$num': typeof ApiPublicObraAudioNumRoute
  '/api/public/obra-imagem/$num': typeof ApiPublicObraImagemNumRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acervo'
    | '/admin'
    | '/auth'
    | '/como-usar'
    | '/editar'
    | '/elifas-andreato'
    | '/espacos-de-memoria'
    | '/instituto'
    | '/linhas-da-vida'
    | '/participe'
    | '/qrcodes'
    | '/sobre'
    | '/obras/$num'
    | '/qrcodes/imprimir'
    | '/acervo/'
    | '/elifas-andreato/'
    | '/espacos-de-memoria/'
    | '/instituto/'
    | '/obras/'
    | '/participe/'
    | '/qrcodes/'
    | '/api/public/obra-audio/$num'
    | '/api/public/obra-imagem/$num'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/como-usar'
    | '/editar'
    | '/linhas-da-vida'
    | '/sobre'
    | '/obras/$num'
    | '/qrcodes/imprimir'
    | '/acervo'
    | '/elifas-andreato'
    | '/espacos-de-memoria'
    | '/instituto'
    | '/obras'
    | '/participe'
    | '/qrcodes'
    | '/api/public/obra-audio/$num'
    | '/api/public/obra-imagem/$num'
  id:
    | '__root__'
    | '/'
    | '/acervo'
    | '/admin'
    | '/auth'
    | '/como-usar'
    | '/editar'
    | '/elifas-andreato'
    | '/espacos-de-memoria'
    | '/instituto'
    | '/linhas-da-vida'
    | '/participe'
    | '/qrcodes'
    | '/sobre'
    | '/obras/$num'
    | '/qrcodes/imprimir'
    | '/acervo/'
    | '/elifas-andreato/'
    | '/espacos-de-memoria/'
    | '/instituto/'
    | '/obras/'
    | '/participe/'
    | '/qrcodes/'
    | '/api/public/obra-audio/$num'
    | '/api/public/obra-imagem/$num'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcervoRoute: typeof AcervoRouteWithChildren
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ComoUsarRoute: typeof ComoUsarRoute
  EditarRoute: typeof EditarRoute
  ElifasAndreatoRoute: typeof ElifasAndreatoRouteWithChildren
  EspacosDeMemoriaRoute: typeof EspacosDeMemoriaRouteWithChildren
  InstitutoRoute: typeof InstitutoRouteWithChildren
  LinhasDaVidaRoute: typeof LinhasDaVidaRoute
  ParticipeRoute: typeof ParticipeRouteWithChildren
  QrcodesRoute: typeof QrcodesRouteWithChildren
  SobreRoute: typeof SobreRoute
  ObrasNumRoute: typeof ObrasNumRoute
  ObrasIndexRoute: typeof ObrasIndexRoute
  ApiPublicObraAudioNumRoute: typeof ApiPublicObraAudioNumRoute
  ApiPublicObraImagemNumRoute: typeof ApiPublicObraImagemNumRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qrcodes': {
      id: '/qrcodes'
      path: '/qrcodes'
      fullPath: '/qrcodes'
      preLoaderRoute: typeof QrcodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participe': {
      id: '/participe'
      path: '/participe'
      fullPath: '/participe'
      preLoaderRoute: typeof ParticipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linhas-da-vida': {
      id: '/linhas-da-vida'
      path: '/linhas-da-vida'
      fullPath: '/linhas-da-vida'
      preLoaderRoute: typeof LinhasDaVidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instituto': {
      id: '/instituto'
      path: '/instituto'
      fullPath: '/instituto'
      preLoaderRoute: typeof InstitutoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espacos-de-memoria': {
      id: '/espacos-de-memoria'
      path: '/espacos-de-memoria'
      fullPath: '/espacos-de-memoria'
      preLoaderRoute: typeof EspacosDeMemoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elifas-andreato': {
      id: '/elifas-andreato'
      path: '/elifas-andreato'
      fullPath: '/elifas-andreato'
      preLoaderRoute: typeof ElifasAndreatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editar': {
      id: '/editar'
      path: '/editar'
      fullPath: '/editar'
      preLoaderRoute: typeof EditarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-usar': {
      id: '/como-usar'
      path: '/como-usar'
      fullPath: '/como-usar'
      preLoaderRoute: typeof ComoUsarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acervo': {
      id: '/acervo'
      path: '/acervo'
      fullPath: '/acervo'
      preLoaderRoute: typeof AcervoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qrcodes/': {
      id: '/qrcodes/'
      path: '/'
      fullPath: '/qrcodes/'
      preLoaderRoute: typeof QrcodesIndexRouteImport
      parentRoute: typeof QrcodesRoute
    }
    '/participe/': {
      id: '/participe/'
      path: '/'
      fullPath: '/participe/'
      preLoaderRoute: typeof ParticipeIndexRouteImport
      parentRoute: typeof ParticipeRoute
    }
    '/obras/': {
      id: '/obras/'
      path: '/obras'
      fullPath: '/obras/'
      preLoaderRoute: typeof ObrasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instituto/': {
      id: '/instituto/'
      path: '/'
      fullPath: '/instituto/'
      preLoaderRoute: typeof InstitutoIndexRouteImport
      parentRoute: typeof InstitutoRoute
    }
    '/espacos-de-memoria/': {
      id: '/espacos-de-memoria/'
      path: '/'
      fullPath: '/espacos-de-memoria/'
      preLoaderRoute: typeof EspacosDeMemoriaIndexRouteImport
      parentRoute: typeof EspacosDeMemoriaRoute
    }
    '/elifas-andreato/': {
      id: '/elifas-andreato/'
      path: '/'
      fullPath: '/elifas-andreato/'
      preLoaderRoute: typeof ElifasAndreatoIndexRouteImport
      parentRoute: typeof ElifasAndreatoRoute
    }
    '/acervo/': {
      id: '/acervo/'
      path: '/'
      fullPath: '/acervo/'
      preLoaderRoute: typeof AcervoIndexRouteImport
      parentRoute: typeof AcervoRoute
    }
    '/qrcodes/imprimir': {
      id: '/qrcodes/imprimir'
      path: '/imprimir'
      fullPath: '/qrcodes/imprimir'
      preLoaderRoute: typeof QrcodesImprimirRouteImport
      parentRoute: typeof QrcodesRoute
    }
    '/obras/$num': {
      id: '/obras/$num'
      path: '/obras/$num'
      fullPath: '/obras/$num'
      preLoaderRoute: typeof ObrasNumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/obra-imagem/$num': {
      id: '/api/public/obra-imagem/$num'
      path: '/api/public/obra-imagem/$num'
      fullPath: '/api/public/obra-imagem/$num'
      preLoaderRoute: typeof ApiPublicObraImagemNumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/obra-audio/$num': {
      id: '/api/public/obra-audio/$num'
      path: '/api/public/obra-audio/$num'
      fullPath: '/api/public/obra-audio/$num'
      preLoaderRoute: typeof ApiPublicObraAudioNumRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AcervoRouteChildren {
  AcervoIndexRoute: typeof AcervoIndexRoute
}

const AcervoRouteChildren: AcervoRouteChildren = {
  AcervoIndexRoute: AcervoIndexRoute,
}

const AcervoRouteWithChildren =
  AcervoRoute._addFileChildren(AcervoRouteChildren)

interface ElifasAndreatoRouteChildren {
  ElifasAndreatoIndexRoute: typeof ElifasAndreatoIndexRoute
}

const ElifasAndreatoRouteChildren: ElifasAndreatoRouteChildren = {
  ElifasAndreatoIndexRoute: ElifasAndreatoIndexRoute,
}

const ElifasAndreatoRouteWithChildren = ElifasAndreatoRoute._addFileChildren(
  ElifasAndreatoRouteChildren,
)

interface EspacosDeMemoriaRouteChildren {
  EspacosDeMemoriaIndexRoute: typeof EspacosDeMemoriaIndexRoute
}

const EspacosDeMemoriaRouteChildren: EspacosDeMemoriaRouteChildren = {
  EspacosDeMemoriaIndexRoute: EspacosDeMemoriaIndexRoute,
}

const EspacosDeMemoriaRouteWithChildren =
  EspacosDeMemoriaRoute._addFileChildren(EspacosDeMemoriaRouteChildren)

interface InstitutoRouteChildren {
  InstitutoIndexRoute: typeof InstitutoIndexRoute
}

const InstitutoRouteChildren: InstitutoRouteChildren = {
  InstitutoIndexRoute: InstitutoIndexRoute,
}

const InstitutoRouteWithChildren = InstitutoRoute._addFileChildren(
  InstitutoRouteChildren,
)

interface ParticipeRouteChildren {
  ParticipeIndexRoute: typeof ParticipeIndexRoute
}

const ParticipeRouteChildren: ParticipeRouteChildren = {
  ParticipeIndexRoute: ParticipeIndexRoute,
}

const ParticipeRouteWithChildren = ParticipeRoute._addFileChildren(
  ParticipeRouteChildren,
)

interface QrcodesRouteChildren {
  QrcodesImprimirRoute: typeof QrcodesImprimirRoute
  QrcodesIndexRoute: typeof QrcodesIndexRoute
}

const QrcodesRouteChildren: QrcodesRouteChildren = {
  QrcodesImprimirRoute: QrcodesImprimirRoute,
  QrcodesIndexRoute: QrcodesIndexRoute,
}

const QrcodesRouteWithChildren =
  QrcodesRoute._addFileChildren(QrcodesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcervoRoute: AcervoRouteWithChildren,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ComoUsarRoute: ComoUsarRoute,
  EditarRoute: EditarRoute,
  ElifasAndreatoRoute: ElifasAndreatoRouteWithChildren,
  EspacosDeMemoriaRoute: EspacosDeMemoriaRouteWithChildren,
  InstitutoRoute: InstitutoRouteWithChildren,
  LinhasDaVidaRoute: LinhasDaVidaRoute,
  ParticipeRoute: ParticipeRouteWithChildren,
  QrcodesRoute: QrcodesRouteWithChildren,
  SobreRoute: SobreRoute,
  ObrasNumRoute: ObrasNumRoute,
  ObrasIndexRoute: ObrasIndexRoute,
  ApiPublicObraAudioNumRoute: ApiPublicObraAudioNumRoute,
  ApiPublicObraImagemNumRoute: ApiPublicObraImagemNumRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
